---
title: "Kansallispuisto-rojekti :)"
author: "Petrus"
date: "Päivitetty `r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, sp, leaflet, flexdashboard, plotly)


# Get data
data <- openxlsx::read.xlsx("data/parks.xlsx")

# Logos
logo_url <- list.files("logos", full.names = T, recursive = T)

# Split coordinate column
data <- data %>%
  tidyr::separate(Coordinates, c('Lat', 'Long'), sep = ", ") %>%
  mutate(
    Lat = as.numeric(Lat), Long = as.numeric(Long),
    Logo_url = logo_url
  )

# Load custom functions
"src" |> list.files(full.names = T) |> walk(source)

# .gpx files
# https://medium.com/@mark.reuter/parsing-gps-gpx-files-with-r-21ea0a694da8
routes <- list.files("data/gpx", recursive = T, full.names = T)

gpx <- list()
for (i in 1:length(routes)) {
  # cat(paste0(routes[i], "  "))
  gpx[[i]] <- xml2::read_html(routes[i]) %>% # Parse
    xml2::xml_find_all("//trkpt") %>% # The lat and long data
    xml2::xml_attrs() %>% bind_rows() %>%
    mutate(route = i)
}
gpxdf <- bind_rows(gpx) %>%
  mutate(lat = as.numeric(lat), lon = as.numeric(lon))
```




Column {data-width=650}
-----------------------------------------------------------------------

### Kartta (`r nrow(data %>% filter(Country == "Finland" & Visit == "Joo"))` / `r nrow(data %>% filter(Country == "Finland"))` Suomen puistoista käyty)

```{r}
# Visited icons
visited <- data %>% filter(Visit == "Joo")
visited_icons <- icons(
  iconUrl = visited$Logo_url,
  iconWidth = 60, iconHeight = NA,
  iconAnchorX = 0, iconAnchorY = 0
)

# Not yet
notyet <- data %>% filter(Visit != "Joo")
notyet_icons <- icons(
  iconUrl = "help-circle.svg",
  iconWidth = 30, iconHeight = 30,
  iconAnchorX = 0, iconAnchorY = 0
)


# Simple pins
# visited_icons <- icons(
#   iconUrl = "pin.png",
#   iconWidth = 30, iconHeight = 30,
#   iconAnchorX = 0, iconAnchorY = 0
# )


# Plot
basemap <- data %>%
  leaflet() %>%
  addTiles() %>%
  # addMarkers(
  #   data = visited, ~Long, ~Lat,
  #   label = paste0(visited$Park_short, "\n", visited$Dates),
  #   icon = visited_icons
  # ) %>%
  # addMarkers(
  #   data = notyet, ~Long, ~Lat,
  #   label = notyet$Park_short,
  #   icon = notyet_icons
  # )
    
  addMarkers(
    data = visited, ~Long, ~Lat,
    label = paste0(visited$Park_short, "\n", visited$Dates),
    icon = visited_icons
  ) %>%
  addMarkers(
    data = notyet, ~Long, ~Lat,
    label = notyet$Park_short,
    icon = notyet_icons
  )

# Add gpx routes
for (i in 1:length(routes)) {
  basemap <- basemap %>%
    addPolylines(
      data = gpxdf %>% filter(route == i),
      lat = ~lat,
      lng = ~lon,
      color = "#FF4500",
      opacity = .9,
      weight = 3
    )
}
basemap
```

Column {data-width=350}
-----------------------------------------------------------------------

### Vieraillut puistot vuosittain

```{r}
# Only novel parks (first visits)
data_first_visits <- data %>%
  drop_na(Dates) %>%
  mutate(Dates = strsplit(Dates, ", ")) %>%
  unnest(Dates) %>%
  tidyr::separate(Dates, c("Month", "Year"), "/") %>%
  group_by(Park) %>% reframe(Year = as.numeric(min(Year))) %>%
  group_by(Year) %>% reframe(n = n()) %>%
  # Fill in missing rows with 0 visits
  complete(Year = seq(min(Year), max(Year), by = 1), fill = list(n = 0)) %>%
  mutate(cumsum = cumsum(n))

# Visits by year
data %>%
  mutate(Dates = strsplit(Dates, ", ")) %>%
  unnest(Dates) %>%
  tidyr::separate(Dates, c("Month", "Year"), "/") %>%
  mutate(Month = as.numeric(Month), Year = as.numeric(Year)) %>%
  drop_na(Year) %>%
  group_by(Year) %>% mutate(visit_order = row_number(Month)-.5) %>%
  ggplot(aes(x = Year)) +
  geom_bar(fill = "darkolivegreen") +
  # geom_col(data = data_first_visits, aes(x = Year, y = n, fill = "Ensimmäinen visiitti")) +
  ggimage::geom_image(
    aes(y = visit_order, image = Logo_url),
    size = 0.12
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(2010, 2100, by = 1)) +
  scale_y_continuous(breaks = seq(1, 30, by = 1)) +
  ylab("Käydyt puistot") + xlab("Vuosi")
```


### Käynnit vuodenajan mukaan

```{r}
# data %>%
#   mutate(Dates = strsplit(Dates, ", ")) %>%
#   unnest(Dates) %>%
#   tidyr::separate(Dates, c("Month", "Year"), "/") %>%
#   mutate(Month = as.numeric(Month), Year = as.numeric(Year)) %>%
#   complete(Month = 1:12) %>%
#   drop_na(Year) %>%
#   group_by(Year) %>% mutate(visit_order = row_number(Month)-.5) %>%
#   ggplot(aes(y = reorder(Month, desc(Month)), x = Year)) +
#   
#   geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = Inf, ymax = 8.5), fill = "#ebf7ff") +
#   geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 8.5, ymax = 7.5), fill = "#dafff5") +
#   geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 7.5, ymax = 4.5), fill = "#e7ffda") +
#   geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 4.5, ymax = 1.5), fill = "#ffdec8") +
#   geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 1.5, ymax = -Inf), fill = "#ebf7ff") +
# 
#   # geom_col(data = data_first_visits, aes(x = Year, y = n, fill = "Ensimmäinen visiitti")) +
#   ggimage::geom_image(aes(image = Logo_url), size = 0.12, position = position_dodge(-1)) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#   scale_y_discrete(breaks = c(1:12), labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
#   scale_x_continuous(breaks = c(2010:2100)) +
#   ylab("Kuukausi") + xlab("Vuosi")



options(scipen = 999)
data %>%
  mutate(Dates = strsplit(Dates, ", ")) %>%
  unnest(Dates) %>%
  tidyr::separate(Dates, c("Month", "Year"), "/") %>%
  mutate(Month = as.numeric(Month), Year = as.numeric(Year)) %>%
  drop_na(Year) %>%
  # group_by(Year, Month) %>%
  # arrange(desc(Month), desc(Logo_url)) %>% ungroup() %>%
  ggplot(aes(group = Park, y = Month, x = Year)) +
  
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = 2.5), fill = "#ebf7ff") +
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 2.5, ymax = 5.5), fill = "#dafff5") +
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 5.5, ymax = 8.5), fill = "#e7ffda") +
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 8.5, ymax = 11.5), fill = "#ffdec8") +
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 11.5, ymax = Inf), fill = "#ebf7ff") +
  # geom_point(size = 3, position = ggstance::position_dodgev(height = 1)) +
  # geom_jitter(aes(size = Area, color = Area)) +

  ggimage::geom_image(aes(image = Logo_url), size = 0.12, position = ggstance::position_dodgev(height = 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = c(1:12), expand = expansion(mult = c(.1, .1))) +
  scale_x_continuous(breaks = c(2010:2100)) +
  coord_cartesian(ylim = c(1, 12)) +
  # scale_colour_gradientn(name = "Pinta-ala", colors = rev(c("#67001f", "#b2182b", "#d6604d", "#f4a582"))) +
  ylab("Kuukausi") + xlab("Vuosi")


  # geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = Inf, ymax = 8.5), fill = "#ebf7ff") +
  # geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 8.5, ymax = 7.5), fill = "#dafff5") +
  # geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 7.5, ymax = 4.5), fill = "#e7ffda") +
  # geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 4.5, ymax = 1.5), fill = "#ffdec8") +
  # geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = 1.5, ymax = -Inf), fill = "#ebf7ff") +

```

